version: "1.0.{build}"
os: Visual Studio 2015
platform: 
  - Win32

environment:
  global:
    MSVC_DEFAULT_OPTIONS: ON
  matrix:
    - VS_VERSION: "Visual Studio 14 2015"
    - VS_VERSION: "Visual Studio 12 2013"

configuration:
  - Debug
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\wigwag

before_build:
  - cmd: cd C:\projects\wigwag
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=%VS_VERSION%
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=%VS_VERSION% Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% ..

build:
  project: C:\projects\wigwag\build\wigwag.sln
  parallel: true
  verbosity: minimal
