version: "1.0.{build}"
os: Visual Studio 2015

environment:
  global:
    MSVC_DEFAULT_OPTIONS: ON
  matrix:
    - VS_VERSION: "Visual Studio 12 2013"
    - VS_VERSION: "Visual Studio 14 2015"

configuration:
  - Debug
  - Release

init:
  - cmd: cmake --version

install:
  - cmd: git clone --depth 1 --branch 4.4 https://github.com/CxxTest/cxxtest.git

clone_folder: C:\projects\wigwag

before_build:
  - cmd: cd C:\projects\wigwag

build_script:
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=%VS_VERSION%
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=%VS_VERSION% Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DCXXTEST_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%\cxxtest -DCXXTEST_PYTHON_TESTGEN_EXECUTABLE=%APPVEYOR_BUILD_FOLDER%\cxxtest\python\scripts\cxxtestgen ..
  - cmd: cmake --build . --target ALL_BUILD

test_script:
  - cmd: "%APPVEYOR_BUILD_FOLDER%\\build\\bin\\%CONFIGURATION%\\wigwag_test"
